import { describe, expect, it } from "vitest";

import { DEFAULT_CONFIG, parseConfig } from "../../src/index.js";

describe("parseConfig", () => {
  it("parses a minimal valid config and applies defaults", () => {
    const config = parseConfig("version: 1\n");

    expect(config.version).toBe(1);
    expect(config.mode).toBe("warn");
    expect(config.agent_detection).toEqual({
      authors: [],
      labels: [],
      branch_patterns: [],
      body_patterns: [],
    });
    expect(config.contract).toEqual({
      required_for: ["agent"],
      allow_missing_in_observe_mode: true,
    });
  });

  it("parses the full supported config shape", () => {
    const config = parseConfig(`
version: 1
mode: block

agent_detection:
  authors:
    - "copilot-swe-agent[bot]"
    - "github-actions[bot]"
  labels:
    - "ai-generated"
    - "agent"
    - "codex"
    - "claude"
  branch_patterns:
    - "codex/**"
    - "agent/**"
    - "copilot/**"
    - "claude/**"
  body_patterns:
    - "generated by codex"
    - "generated with claude"
    - "copilot coding agent"

contract:
  required_for:
    - agent
  allow_missing_in_observe_mode: true

high_risk_paths:
  auth:
    paths:
      - "src/auth/**"
      - "app/**/auth/**"
    require_tests:
      - "tests/auth/**"
      - "**/*.auth.test.ts"
    severity: error

agent_control_plane:
  paths:
    - "AGENTS.md"
    - "**/AGENTS.md"
    - "AGENTS.override.md"
    - "**/AGENTS.override.md"
    - "CLAUDE.md"
    - ".cursor/**"
    - ".github/copilot-instructions.md"
    - ".mcp.json"
    - "claude_desktop_config.json"
    - ".codex/**"
  severity: error

github_actions:
  paths:
    - ".github/workflows/*.yml"
    - ".github/workflows/*.yaml"
  block_permission_escalation: true
  block_pull_request_target_checkout: true
  require_pinned_actions: warn
  severity: error

package_scripts:
  enabled: true
  paths:
    - package.json
    - "**/package.json"
  lifecycle_scripts:
    - preinstall
    - install
    - postinstall
    - prepare
  severity: warn
`);

    expect(config.mode).toBe("block");
    expect(config.agent_detection.authors).toEqual([
      "copilot-swe-agent[bot]",
      "github-actions[bot]",
    ]);
    expect(config.high_risk_paths.auth).toEqual({
      paths: ["src/auth/**", "app/**/auth/**"],
      require_tests: ["tests/auth/**", "**/*.auth.test.ts"],
      severity: "error",
    });
    expect(config.package_scripts).toEqual({
      enabled: true,
      paths: ["package.json", "**/package.json"],
      lifecycle_scripts: ["preinstall", "install", "postinstall", "prepare"],
      severity: "warn",
    });
  });

  it("exposes defaults with the same values as a minimal config parse", () => {
    expect(DEFAULT_CONFIG).toEqual(parseConfig("version: 1\n"));
  });

  it("rejects an invalid mode with a config-prefixed message and issue path", () => {
    expect(() => parseConfig("version: 1\nmode: strict\n")).toThrow(
      /Invalid agent-gate\.yml: mode/,
    );
  });

  it("rejects invalid severity values", () => {
    expect(() =>
      parseConfig(`
version: 1
agent_control_plane:
  severity: critical
`),
    ).toThrow(/Invalid agent-gate\.yml: agent_control_plane\.severity/);
  });

  it("rejects invalid versions", () => {
    expect(() => parseConfig("version: 2\n")).toThrow(/Invalid agent-gate\.yml: version/);
  });

  it("parses high risk path records by area name", () => {
    const config = parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - "src/auth/**"
    severity: error
  payments:
    paths:
      - "src/payments/**"
    severity: warn
`);

    expect(Object.keys(config.high_risk_paths)).toEqual(["auth", "payments"]);
    expect(config.high_risk_paths.auth?.paths).toEqual(["src/auth/**"]);
    expect(config.high_risk_paths.payments?.severity).toBe("warn");
  });

  it("rejects unknown fields instead of stripping them", () => {
    expect(() => parseConfig("version: 1\nunexpected: true\n")).toThrow(
      /Invalid agent-gate\.yml: unexpected/,
    );
  });

  it("defaults agent control plane paths to known agent instruction and MCP files", () => {
    const config = parseConfig("version: 1\n");

    expect(config.agent_control_plane.paths).toEqual([
      "AGENTS.md",
      "**/AGENTS.md",
      "AGENTS.override.md",
      "**/AGENTS.override.md",
      "CLAUDE.md",
      "**/CLAUDE.md",
      ".cursor/**",
      ".github/copilot-instructions.md",
      ".mcp.json",
      "claude_desktop_config.json",
      ".codex/**",
    ]);
  });

  it("defaults package lifecycle script checks to warning mode", () => {
    const config = parseConfig("version: 1\n");

    expect(config.package_scripts).toEqual({
      enabled: true,
      paths: ["package.json", "**/package.json"],
      lifecycle_scripts: ["preinstall", "install", "postinstall", "prepare"],
      severity: "warn",
    });
  });

  it("rejects empty high-risk path patterns", () => {
    expect(() =>
      parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - ""
`),
    ).toThrow(/Invalid agent-gate\.yml: high_risk_paths\.auth\.paths\.0/);
  });

  it("rejects whitespace-only agent detection labels", () => {
    expect(() =>
      parseConfig(`
version: 1
agent_detection:
  labels:
    - "   "
`),
    ).toThrow(/Invalid agent-gate\.yml: agent_detection\.labels\.0/);
  });

  it("rejects planned config fields that are not implemented yet", () => {
    expect(() =>
      parseConfig(`
version: 1
risk_budget:
  max_files_changed_for_agent: 12
`),
    ).toThrow(/Invalid agent-gate\.yml: risk_budget/);

    expect(() =>
      parseConfig(`
version: 1
dependencies:
  require_lockfile_update: true
`),
    ).toThrow(/Invalid agent-gate\.yml: dependencies/);

    expect(() =>
      parseConfig(`
version: 1
evidence:
  claim_vs_ci:
    enabled: true
`),
    ).toThrow(/Invalid agent-gate\.yml: evidence/);
  });

  it("rejects planned reviewer, rollback, and file-contract fields", () => {
    expect(() =>
      parseConfig(`
version: 1
contract:
  sources:
    - file
`),
    ).toThrow(/Invalid agent-gate\.yml: contract\.sources/);

    expect(() =>
      parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - src/auth/**
    require_reviewers:
      - "@security-team"
`),
    ).toThrow(/Invalid agent-gate\.yml: high_risk_paths\.auth\.require_reviewers/);

    expect(() =>
      parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - src/auth/**
    require_rollback_plan: true
`),
    ).toThrow(/Invalid agent-gate\.yml: high_risk_paths\.auth\.require_rollback_plan/);

    expect(() =>
      parseConfig(`
version: 1
agent_control_plane:
  require_reviewers:
    - "@platform-team"
`),
    ).toThrow(/Invalid agent-gate\.yml: agent_control_plane\.require_reviewers/);
  });
});
