import { describe, expect, it } from "vitest";

import {
  MergeWardenConfigSchema,
  DEFAULT_CONFIG,
  DEFAULT_GITHUB_ACTION_CHECKS,
  parseConfig,
} from "../../src/index.js";

describe("parseConfig", () => {
  it("parses a minimal valid config and applies defaults", () => {
    const config = parseConfig("version: 1\n");

    expect(config.version).toBe(1);
    expect(config.mode).toBe("warn");
    expect(config.agent_detection).toEqual({
      authors: [],
      labels: [],
      branch_patterns: [],
      body_patterns: [],
    });
    expect(config.contract).toEqual({
      required_for: ["agent"],
      allow_missing_in_observe_mode: true,
    });
  });

  it("parses the full supported config shape", () => {
    const config = parseConfig(`
version: 1
mode: block

agent_detection:
  authors:
    - "copilot-swe-agent[bot]"
    - "github-actions[bot]"
  labels:
    - "ai-generated"
    - "agent"
    - "codex"
    - "claude"
  branch_patterns:
    - "codex/**"
    - "agent/**"
    - "copilot/**"
    - "claude/**"
  body_patterns:
    - "generated by codex"
    - "generated with claude"
    - "copilot coding agent"

contract:
  required_for:
    - agent
  allow_missing_in_observe_mode: true

high_risk_paths:
  auth:
    paths:
      - "src/auth/**"
      - "app/**/auth/**"
    require_tests:
      - "tests/auth/**"
      - "**/*.auth.test.ts"
    severity: error

agent_control_plane:
  paths:
    - "AGENTS.md"
    - "**/AGENTS.md"
    - "AGENTS.override.md"
    - "**/AGENTS.override.md"
    - "CLAUDE.md"
    - ".cursor/**"
    - ".github/copilot-instructions.md"
    - ".mcp.json"
    - "claude_desktop_config.json"
    - ".codex/**"
  severity: error

github_actions:
  paths:
    - ".github/workflows/*.yml"
    - ".github/workflows/*.yaml"
  block_permission_escalation: true
  block_pull_request_target_checkout: true
  require_pinned_actions: warn
  severity: error

package_scripts:
  enabled: true
  paths:
    - package.json
    - "**/package.json"
  lifecycle_scripts:
    - preinstall
    - install
    - postinstall
    - prepare
  severity: warn
`);

    expect(config.mode).toBe("block");
    expect(config.agent_detection.authors).toEqual([
      "copilot-swe-agent[bot]",
      "github-actions[bot]",
    ]);
    expect(config.high_risk_paths.auth).toEqual({
      paths: ["src/auth/**", "app/**/auth/**"],
      require_tests: ["tests/auth/**", "**/*.auth.test.ts"],
      severity: "error",
    });
    expect(config.package_scripts).toEqual({
      enabled: true,
      paths: ["package.json", "**/package.json"],
      lifecycle_scripts: ["preinstall", "install", "postinstall", "prepare"],
      severity: "warn",
    });
  });

  it("exposes defaults with the same values as a minimal config parse", () => {
    expect(DEFAULT_CONFIG).toEqual(parseConfig("version: 1\n"));
    expect(DEFAULT_CONFIG.github_actions.checks).toEqual(DEFAULT_GITHUB_ACTION_CHECKS);
  });

  it("parses granular workflow checks and fills individual defaults", () => {
    const config = parseConfig(`
version: 1
github_actions:
  checks:
    permission_escalation: warn
    unpinned_action: off
`);

    expect(config.github_actions.checks).toEqual({
      ...DEFAULT_GITHUB_ACTION_CHECKS,
      permission_escalation: "warn",
      unpinned_action: "off",
    });
  });

  it("maps legacy workflow settings onto granular checks", () => {
    const config = parseConfig(`
version: 1
github_actions:
  block_permission_escalation: false
  block_pull_request_target_checkout: false
  require_pinned_actions: error
  severity: warn
`);

    expect(config.github_actions.checks).toMatchObject({
      permission_escalation: "off",
      write_all: "warn",
      id_token_write: "warn",
      pull_request_target_head: "off",
      unpinned_action: "error",
      unpinned_reusable_workflow: "error",
      unpinned_container: "error",
      malformed_workflow: "warn",
    });
  });

  it("rejects any raw mixing of granular and legacy workflow settings", () => {
    const yaml = `
version: 1
github_actions:
  severity: error
  checks:
    write_all: error
`;

    expect(() => parseConfig(yaml)).toThrow(/cannot be mixed with legacy/);
    expect(
      MergeWardenConfigSchema.safeParse({
        version: 1,
        github_actions: {
          severity: "error",
          checks: { write_all: "error" },
        },
      }).success,
    ).toBe(false);
  });

  it("validates waivers and agentic workflow extensions", () => {
    const config = parseConfig(`
version: 1
waivers:
  - finding_id: agf_0123456789abcdef
    reason: Approved exception
    expires_at: 2026-09-30T00:00:00Z
agentic_workflows:
  enabled: true
  severity: warn
  privileged_severity: error
  additional_actions:
    - uses: owner/custom-agent-action
      prompt_inputs: [prompt, instructions]
`);

    expect(config.waivers).toEqual([
      {
        finding_id: "agf_0123456789abcdef",
        reason: "Approved exception",
        expires_at: "2026-09-30T00:00:00Z",
      },
    ]);
    expect(config.agentic_workflows.additional_actions).toEqual([
      {
        uses: "owner/custom-agent-action",
        prompt_inputs: ["prompt", "instructions"],
      },
    ]);
  });

  it("rejects duplicate, malformed, and non-RFC3339 waivers", () => {
    expect(() =>
      parseConfig(`
version: 1
waivers:
  - finding_id: agf_0123456789abcdef
    reason: first
    expires_at: 2026-09-30T00:00:00Z
  - finding_id: agf_0123456789abcdef
    reason: second
    expires_at: 2026-10-30T00:00:00Z
`),
    ).toThrow(/duplicate waiver/);

    expect(() =>
      parseConfig(`
version: 1
waivers:
  - finding_id: not-a-finding
    reason: invalid id
    expires_at: tomorrow
`),
    ).toThrow(/waivers\.0\.finding_id|waivers\.0\.expires_at/);
  });

  it("rejects an invalid mode with a config-prefixed message and issue path", () => {
    expect(() => parseConfig("version: 1\nmode: strict\n")).toThrow(
      /Invalid mergewarden\.yml: mode/,
    );
  });

  it("rejects invalid severity values", () => {
    expect(() =>
      parseConfig(`
version: 1
agent_control_plane:
  severity: critical
`),
    ).toThrow(/Invalid mergewarden\.yml: agent_control_plane\.severity/);
  });

  it("rejects invalid versions", () => {
    expect(() => parseConfig("version: 2\n")).toThrow(/Invalid mergewarden\.yml: version/);
  });

  it("parses high risk path records by area name", () => {
    const config = parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - "src/auth/**"
    severity: error
  payments:
    paths:
      - "src/payments/**"
    severity: warn
`);

    expect(Object.keys(config.high_risk_paths)).toEqual(["auth", "payments"]);
    expect(config.high_risk_paths.auth?.paths).toEqual(["src/auth/**"]);
    expect(config.high_risk_paths.payments?.severity).toBe("warn");
  });

  it("rejects unknown fields instead of stripping them", () => {
    expect(() => parseConfig("version: 1\nunexpected: true\n")).toThrow(
      /Invalid mergewarden\.yml: unexpected/,
    );
  });

  it("defaults agent control plane paths to known agent instruction and MCP files", () => {
    const config = parseConfig("version: 1\n");

    expect(config.agent_control_plane.paths).toEqual([
      "AGENTS.md",
      "**/AGENTS.md",
      "AGENTS.override.md",
      "**/AGENTS.override.md",
      "CLAUDE.md",
      "**/CLAUDE.md",
      ".cursor/**",
      ".github/copilot-instructions.md",
      ".mcp.json",
      "claude_desktop_config.json",
      ".codex/**",
    ]);
  });

  it("defaults package lifecycle script checks to warning mode", () => {
    const config = parseConfig("version: 1\n");

    expect(config.package_scripts).toEqual({
      enabled: true,
      paths: ["package.json", "**/package.json"],
      lifecycle_scripts: ["preinstall", "install", "postinstall", "prepare"],
      severity: "warn",
    });
  });

  it("rejects empty high-risk path patterns", () => {
    expect(() =>
      parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - ""
`),
    ).toThrow(/Invalid mergewarden\.yml: high_risk_paths\.auth\.paths\.0/);
  });

  it("rejects whitespace-only agent detection labels", () => {
    expect(() =>
      parseConfig(`
version: 1
agent_detection:
  labels:
    - "   "
`),
    ).toThrow(/Invalid mergewarden\.yml: agent_detection\.labels\.0/);
  });

  it("rejects planned config fields that are not implemented yet", () => {
    expect(() =>
      parseConfig(`
version: 1
risk_budget:
  max_files_changed_for_agent: 12
`),
    ).toThrow(/Invalid mergewarden\.yml: risk_budget/);

    expect(() =>
      parseConfig(`
version: 1
dependencies:
  require_lockfile_update: true
`),
    ).toThrow(/Invalid mergewarden\.yml: dependencies/);

    expect(() =>
      parseConfig(`
version: 1
evidence:
  claim_vs_ci:
    enabled: true
`),
    ).toThrow(/Invalid mergewarden\.yml: evidence/);
  });

  it("rejects planned reviewer, rollback, and file-contract fields", () => {
    expect(() =>
      parseConfig(`
version: 1
contract:
  sources:
    - file
`),
    ).toThrow(/Invalid mergewarden\.yml: contract\.sources/);

    expect(() =>
      parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - src/auth/**
    require_reviewers:
      - "@security-team"
`),
    ).toThrow(/Invalid mergewarden\.yml: high_risk_paths\.auth\.require_reviewers/);

    expect(() =>
      parseConfig(`
version: 1
high_risk_paths:
  auth:
    paths:
      - src/auth/**
    require_rollback_plan: true
`),
    ).toThrow(/Invalid mergewarden\.yml: high_risk_paths\.auth\.require_rollback_plan/);

    expect(() =>
      parseConfig(`
version: 1
agent_control_plane:
  require_reviewers:
    - "@platform-team"
`),
    ).toThrow(/Invalid mergewarden\.yml: agent_control_plane\.require_reviewers/);
  });
});
