import { describe, expect, it } from "vitest";

import { analyze, detectAgentOrigin, parseConfig } from "../../src/index.js";
import { createAnalysisInput } from "../helpers.js";

describe("detectAgentOrigin", () => {
  it("detects configured authors", () => {
    const input = createAnalysisInput({
      config: parseConfig("version: 1\nagent_detection:\n  authors:\n    - codex\n"),
      pr: { author: "codex" },
    });

    expect(detectAgentOrigin(input)).toEqual({
      detected: true,
      signals: [{ kind: "author", value: "codex", matched: "codex" }],
    });
  });

  it("detects labels case-insensitively", () => {
    const input = createAnalysisInput({
      config: parseConfig("version: 1\nagent_detection:\n  labels:\n    - ai-generated\n"),
      pr: { labels: ["AI-Generated"] },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "label", value: "AI-Generated", matched: "ai-generated" },
    ]);
  });

  it("detects branch globs", () => {
    const input = createAnalysisInput({
      config: parseConfig("version: 1\nagent_detection:\n  branch_patterns:\n    - codex/**\n"),
      pr: { branchName: "codex/fix-auth" },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "branch", value: "codex/fix-auth", matched: "codex/**" },
    ]);
  });

  it("detects body phrases in titles", () => {
    const input = createAnalysisInput({
      config: parseConfig(
        "version: 1\nagent_detection:\n  body_patterns:\n    - generated by codex\n",
      ),
      pr: { title: "Generated by Codex: fix auth bug", body: "" },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "body", value: "Generated by Codex: fix auth bug", matched: "generated by codex" },
    ]);
  });

  it("detects body phrases in pull request bodies", () => {
    const input = createAnalysisInput({
      config: parseConfig(
        "version: 1\nagent_detection:\n  body_patterns:\n    - generated by codex\n",
      ),
      pr: { title: "Fix auth bug", body: "This was generated by Codex." },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "body", value: "This was generated by Codex.", matched: "generated by codex" },
    ]);
  });

  it("keeps user-facing origin evidence concise", async () => {
    const result = await analyze(
      createAnalysisInput({
        config: parseConfig(
          "version: 1\nagent_detection:\n  body_patterns:\n    - generated by codex\n",
        ),
        pr: {
          title: "Fix auth bug",
          body: `Generated by Codex ${"with lots of details ".repeat(20)}`,
        },
      }),
    );

    const finding = result.findings.find((item) => item.ruleId === "agent/origin-detected");

    expect(finding?.evidence).toContainEqual(
      expect.objectContaining({
        label: "body",
        value: expect.stringMatching(/^body matched "generated by codex" in ".+\.\.\."$/),
      }),
    );
    expect(finding?.evidence[0]?.value.length).toBeLessThanOrEqual(200);
  });

  it("returns no finding when no agent origin is detected", async () => {
    const result = await analyze(
      createAnalysisInput({
        config: parseConfig("version: 1\nagent_detection:\n  labels:\n    - ai-generated\n"),
        pr: { labels: ["human-authored"] },
      }),
    );

    expect(result.findings.map((finding) => finding.ruleId)).not.toContain("agent/origin-detected");
  });
});

describe("default body markers against real agent output", () => {
  // Verbatim footer Claude Code appends to a pull request body. Pinned as a literal because the
  // Markdown link is exactly what the pre-v0.5.1 default missed: the product name sits inside
  // [ ], so "Generated with Claude Code" never appears as a substring. Sampled against 13 real
  // Claude Code pull requests from the scan study; do not "tidy" the brackets out of this string.
  const CLAUDE_CODE_FOOTER =
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>";

  it("detects a Claude Code pull request on the default config alone", async () => {
    const result = await analyze(
      createAnalysisInput({
        pr: {
          title: "Fix session expiry handling",
          body: `Fixes the expiry clamp.\n\n${CLAUDE_CODE_FOOTER}`,
          author: "some-human",
          branchName: "fix/session-expiry",
        },
      }),
    );

    const detected = result.findings.find((finding) => finding.ruleId === "agent/origin-detected");

    expect(detected).toBeDefined();
    expect(detected?.evidence).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          label: "body",
          value: expect.stringContaining('matched "Generated with [Claude Code]"'),
        }),
      ]),
    );
  });

  // Each of these was verified against a real pull request that the account opened before it
  // was added as a default; see the provenance table in config/schema.ts. The two that carry a
  // comment are the ones that motivated the list: Jules opens more pull requests than Devin and
  // was missing entirely, and Kiro is the account whose pull request exposed the gap.
  it.each([
    ["copilot-swe-agent[bot]"],
    ["google-labs-jules[bot]"], // 319,715 public PRs, more than Devin
    ["devin-ai-integration[bot]"],
    ["kiro-agent[bot]"], // found by auditing PRs the engine had classed as human
    ["codegen-sh[bot]"],
    ["opencode-agent[bot]"],
    ["tembo[bot]"],
    ["amazon-q-developer[bot]"],
    ["mentatbot[bot]"],
    ["factory-droid[bot]"],
    ["ellipsis-dev[bot]"],
  ])("detects %s on the default config alone", async (author) => {
    const result = await analyze(
      createAnalysisInput({
        pr: { author, branchName: "some-ordinary-branch", body: "Implements the requested fix." },
      }),
    );

    expect(result.findings.map((finding) => finding.ruleId)).toContain("agent/origin-detected");
  });

  it("does not treat ordinary release automation as an agent", async () => {
    for (const author of ["dependabot[bot]", "renovate[bot]", "github-actions[bot]"]) {
      const result = await analyze(
        createAnalysisInput({
          pr: {
            author,
            branchName: "dependabot/npm_and_yarn/lodash-4.17.21",
            body: "Bumps lodash.",
          },
        }),
      );

      expect(
        result.findings.map((finding) => finding.ruleId),
        `${author} must not be treated as a coding agent`,
      ).not.toContain("agent/origin-detected");
    }
  });

  it("does not treat a pull request that merely mentions the product as agent-authored", async () => {
    const result = await analyze(
      createAnalysisInput({
        pr: {
          title: "docs: compare Claude Code, Codex and Cursor",
          body: "A table of which coding agents support which hooks.",
          author: "some-human",
          branchName: "docs/agent-comparison",
        },
      }),
    );

    expect(result.findings.map((finding) => finding.ruleId)).not.toContain("agent/origin-detected");
  });
});
