import { describe, expect, it } from "vitest";

import { analyze, detectAgentOrigin, parseConfig } from "../../src/index.js";
import { createAnalysisInput } from "../helpers.js";

describe("detectAgentOrigin", () => {
  it("detects configured authors", () => {
    const input = createAnalysisInput({
      config: parseConfig("version: 1\nagent_detection:\n  authors:\n    - codex\n"),
      pr: { author: "codex" },
    });

    expect(detectAgentOrigin(input)).toEqual({
      detected: true,
      signals: [{ kind: "author", value: "codex", matched: "codex" }],
    });
  });

  it("detects labels case-insensitively", () => {
    const input = createAnalysisInput({
      config: parseConfig("version: 1\nagent_detection:\n  labels:\n    - ai-generated\n"),
      pr: { labels: ["AI-Generated"] },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "label", value: "AI-Generated", matched: "ai-generated" },
    ]);
  });

  it("detects branch globs", () => {
    const input = createAnalysisInput({
      config: parseConfig("version: 1\nagent_detection:\n  branch_patterns:\n    - codex/**\n"),
      pr: { branchName: "codex/fix-auth" },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "branch", value: "codex/fix-auth", matched: "codex/**" },
    ]);
  });

  it("detects body phrases in titles", () => {
    const input = createAnalysisInput({
      config: parseConfig(
        "version: 1\nagent_detection:\n  body_patterns:\n    - generated by codex\n",
      ),
      pr: { title: "Generated by Codex: fix auth bug", body: "" },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "body", value: "Generated by Codex: fix auth bug", matched: "generated by codex" },
    ]);
  });

  it("detects body phrases in pull request bodies", () => {
    const input = createAnalysisInput({
      config: parseConfig(
        "version: 1\nagent_detection:\n  body_patterns:\n    - generated by codex\n",
      ),
      pr: { title: "Fix auth bug", body: "This was generated by Codex." },
    });

    expect(detectAgentOrigin(input).signals).toEqual([
      { kind: "body", value: "This was generated by Codex.", matched: "generated by codex" },
    ]);
  });

  it("keeps user-facing origin evidence concise", async () => {
    const result = await analyze(
      createAnalysisInput({
        config: parseConfig(
          "version: 1\nagent_detection:\n  body_patterns:\n    - generated by codex\n",
        ),
        pr: {
          title: "Fix auth bug",
          body: `Generated by Codex ${"with lots of details ".repeat(20)}`,
        },
      }),
    );

    const finding = result.findings.find((item) => item.ruleId === "agent/origin-detected");

    expect(finding?.evidence).toContainEqual(
      expect.objectContaining({
        label: "body",
        value: expect.stringMatching(/^body matched "generated by codex" in ".+\.\.\."$/),
      }),
    );
    expect(finding?.evidence[0]?.value.length).toBeLessThanOrEqual(200);
  });

  it("returns no finding when no agent origin is detected", async () => {
    const result = await analyze(
      createAnalysisInput({
        config: parseConfig("version: 1\nagent_detection:\n  labels:\n    - ai-generated\n"),
        pr: { labels: ["human-authored"] },
      }),
    );

    expect(result.findings.map((finding) => finding.ruleId)).not.toContain("agent/origin-detected");
  });
});
